Logging started at 2015-10-23 20:02:33
File name: C:\Users\root\Dropbox\Vencillio Advanced\VA Source\.\data\logs\err\1445626953699 - root - [Fri Oct 23][8.02PM].txt
System.getProperty("os.name"): "Windows Server 2008 R2"

[2015-10-23 20:35:41] java.lang.NumberFormatException: For input string: "1m"
[2015-10-23 20:35:41] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2015-10-23 20:35:41] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-23 20:35:41] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-23 20:35:41] 	at com.vencillio.rs2.entity.player.net.in.impl.StringInputPacket.handle(StringInputPacket.java:41)
[2015-10-23 20:35:41] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-23 20:35:41] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-23 20:35:41] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-23 20:35:41] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-23 20:35:41] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-23 20:35:58] java.lang.NumberFormatException: For input string: "500k"
[2015-10-23 20:35:58] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2015-10-23 20:35:58] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-23 20:35:58] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-23 20:35:58] 	at com.vencillio.rs2.entity.player.net.in.impl.StringInputPacket.handle(StringInputPacket.java:41)
[2015-10-23 20:35:58] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-23 20:35:58] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-23 20:35:58] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-23 20:35:58] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-23 20:35:58] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-23 23:46:51] java.lang.NumberFormatException: For input string: "'"
[2015-10-23 23:46:51] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2015-10-23 23:46:51] 	at java.lang.Long.parseLong(Unknown Source)
[2015-10-23 23:46:51] 	at java.lang.Long.parseLong(Unknown Source)
[2015-10-23 23:46:51] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:177)
[2015-10-23 23:46:51] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2015-10-23 23:46:51] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-23 23:46:51] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-23 23:46:51] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-23 23:46:51] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-23 23:46:51] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-23 23:51:09] java.lang.NumberFormatException: For input string: "14k"
[2015-10-23 23:51:09] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2015-10-23 23:51:09] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-23 23:51:09] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-23 23:51:09] 	at com.vencillio.rs2.entity.player.net.in.impl.StringInputPacket.handle(StringInputPacket.java:41)
[2015-10-23 23:51:09] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-23 23:51:09] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-23 23:51:09] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-23 23:51:09] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-23 23:51:09] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-24 01:56:30] java.lang.NumberFormatException: For input string: "4m"
[2015-10-24 01:56:30] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2015-10-24 01:56:30] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-24 01:56:30] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-24 01:56:30] 	at com.vencillio.rs2.entity.player.net.in.impl.StringInputPacket.handle(StringInputPacket.java:41)
[2015-10-24 01:56:30] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-24 01:56:30] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-24 01:56:30] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-24 01:56:30] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-24 01:56:30] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-24 05:03:25] java.lang.IndexOutOfBoundsException: Readable byte limit exceeded: 12
[2015-10-24 05:03:25] 	at org.jboss.netty.buffer.AbstractChannelBuffer.readByte(AbstractChannelBuffer.java:236)
[2015-10-24 05:03:25] 	at com.vencillio.core.network.StreamBuffer$InBuffer.readByte(StreamBuffer.java:120)
[2015-10-24 05:03:25] 	at com.vencillio.core.network.StreamBuffer$InBuffer.readByte(StreamBuffer.java:107)
[2015-10-24 05:03:25] 	at com.vencillio.core.network.StreamBuffer$InBuffer.readShort(StreamBuffer.java:467)
[2015-10-24 05:03:25] 	at com.vencillio.core.network.StreamBuffer$InBuffer.readShort(StreamBuffer.java:412)
[2015-10-24 05:03:25] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:748)
[2015-10-24 05:03:25] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-24 05:03:25] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-24 05:03:25] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-24 05:03:25] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-24 05:03:25] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-24 10:26:01] java.lang.NullPointerException
[2015-10-24 10:26:01] 	at com.vencillio.rs2.content.combat.formula.RangeFormulas.calculateRangeAttack(RangeFormulas.java:78)
[2015-10-24 10:26:01] 	at com.vencillio.rs2.content.combat.impl.Ranged.execute(Ranged.java:41)
[2015-10-24 10:26:01] 	at com.vencillio.rs2.content.combat.Combat.attack(Combat.java:92)
[2015-10-24 10:26:01] 	at com.vencillio.rs2.content.combat.Combat.process(Combat.java:215)
[2015-10-24 10:26:01] 	at com.vencillio.rs2.entity.player.Player.process(Player.java:1518)
[2015-10-24 10:26:01] 	at com.vencillio.rs2.entity.World.process(World.java:321)
[2015-10-24 10:26:01] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-24 10:26:01] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-24 10:26:01] java.lang.NullPointerException
[2015-10-24 10:26:01] 	at com.vencillio.rs2.entity.player.net.Client.send(Client.java:329)
[2015-10-24 10:26:01] 	at com.vencillio.rs2.entity.player.net.out.impl.SendLogout.execute(SendLogout.java:13)
[2015-10-24 10:26:01] 	at com.vencillio.rs2.entity.player.Player.logout(Player.java:1444)
[2015-10-24 10:26:01] 	at com.vencillio.rs2.entity.World.process(World.java:332)
[2015-10-24 10:26:01] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-24 10:26:01] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-24 12:28:55] java.lang.NumberFormatException: For input string: "\"
[2015-10-24 12:28:55] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2015-10-24 12:28:55] 	at java.lang.Long.parseLong(Unknown Source)
[2015-10-24 12:28:55] 	at java.lang.Long.parseLong(Unknown Source)
[2015-10-24 12:28:55] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:177)
[2015-10-24 12:28:55] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2015-10-24 12:28:55] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-24 12:28:55] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-24 12:28:55] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-24 12:28:55] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-24 12:28:55] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-24 13:28:01] java.lang.NumberFormatException: For input string: "yes"
[2015-10-24 13:28:01] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2015-10-24 13:28:01] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-24 13:28:01] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-24 13:28:01] 	at com.vencillio.rs2.entity.player.net.in.impl.StringInputPacket.handle(StringInputPacket.java:41)
[2015-10-24 13:28:01] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-24 13:28:01] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-24 13:28:01] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-24 13:28:01] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-24 13:28:01] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-24 13:29:36] java.lang.NumberFormatException: For input string: "1m"
[2015-10-24 13:29:36] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2015-10-24 13:29:36] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-24 13:29:36] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-24 13:29:36] 	at com.vencillio.rs2.entity.player.net.in.impl.StringInputPacket.handle(StringInputPacket.java:41)
[2015-10-24 13:29:36] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-24 13:29:36] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-24 13:29:36] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-24 13:29:36] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-24 13:29:36] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-24 13:30:34] java.lang.NumberFormatException: For input string: "1m"
[2015-10-24 13:30:34] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2015-10-24 13:30:34] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-24 13:30:34] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-24 13:30:34] 	at com.vencillio.rs2.entity.player.net.in.impl.StringInputPacket.handle(StringInputPacket.java:41)
[2015-10-24 13:30:34] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-24 13:30:34] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-24 13:30:34] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-24 13:30:34] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-24 13:30:34] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-24 16:34:59] java.lang.NumberFormatException: For input string: "25k"
[2015-10-24 16:34:59] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2015-10-24 16:34:59] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-24 16:34:59] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-24 16:34:59] 	at com.vencillio.rs2.entity.player.net.in.impl.StringInputPacket.handle(StringInputPacket.java:41)
[2015-10-24 16:34:59] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-24 16:34:59] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-24 16:34:59] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-24 16:34:59] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-24 16:34:59] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-24 16:47:03] java.lang.NullPointerException
[2015-10-24 16:47:03] 	at com.vencillio.rs2.content.combat.formula.RangeFormulas.calculateRangeAttack(RangeFormulas.java:78)
[2015-10-24 16:47:03] 	at com.vencillio.rs2.content.combat.impl.Ranged.execute(Ranged.java:41)
[2015-10-24 16:47:03] 	at com.vencillio.rs2.content.combat.Combat.attack(Combat.java:92)
[2015-10-24 16:47:03] 	at com.vencillio.rs2.content.combat.Combat.process(Combat.java:215)
[2015-10-24 16:47:03] 	at com.vencillio.rs2.entity.player.Player.process(Player.java:1518)
[2015-10-24 16:47:03] 	at com.vencillio.rs2.entity.World.process(World.java:321)
[2015-10-24 16:47:03] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-24 16:47:03] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-24 16:47:03] java.lang.NullPointerException
[2015-10-24 16:47:03] 	at com.vencillio.rs2.entity.player.net.Client.send(Client.java:329)
[2015-10-24 16:47:03] 	at com.vencillio.rs2.entity.player.net.out.impl.SendLogout.execute(SendLogout.java:13)
[2015-10-24 16:47:03] 	at com.vencillio.rs2.entity.player.Player.logout(Player.java:1444)
[2015-10-24 16:47:03] 	at com.vencillio.rs2.entity.World.process(World.java:332)
[2015-10-24 16:47:03] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-24 16:47:03] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-24 17:24:33] java.lang.NumberFormatException: For input string: "50,"
[2015-10-24 17:24:33] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2015-10-24 17:24:33] 	at java.lang.Long.parseLong(Unknown Source)
[2015-10-24 17:24:33] 	at java.lang.Long.parseLong(Unknown Source)
[2015-10-24 17:24:33] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:177)
[2015-10-24 17:24:33] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2015-10-24 17:24:33] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-24 17:24:33] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-24 17:24:33] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-24 17:24:33] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-24 17:24:33] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-24 21:43:08] java.lang.NumberFormatException: For input string: "3m"
[2015-10-24 21:43:08] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2015-10-24 21:43:08] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-24 21:43:08] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-24 21:43:08] 	at com.vencillio.rs2.entity.player.net.in.impl.StringInputPacket.handle(StringInputPacket.java:41)
[2015-10-24 21:43:08] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-24 21:43:08] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-24 21:43:08] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-24 21:43:08] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-24 21:43:08] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-24 23:43:41] java.lang.NullPointerException
[2015-10-24 23:43:41] 	at com.vencillio.rs2.content.DropTable.displayNpc(DropTable.java:177)
[2015-10-24 23:43:41] 	at com.vencillio.rs2.entity.player.net.in.impl.ClickButtonPacket.handle(ClickButtonPacket.java:115)
[2015-10-24 23:43:41] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-24 23:43:41] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-24 23:43:41] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-24 23:43:41] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-24 23:43:41] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-25 05:45:32] java.lang.NumberFormatException: For input string: "j000"
[2015-10-25 05:45:32] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2015-10-25 05:45:32] 	at java.lang.Long.parseLong(Unknown Source)
[2015-10-25 05:45:32] 	at java.lang.Long.parseLong(Unknown Source)
[2015-10-25 05:45:32] 	at com.vencillio.rs2.entity.player.net.in.command.impl.PlayerCommand.handleCommand(PlayerCommand.java:177)
[2015-10-25 05:45:32] 	at com.vencillio.rs2.entity.player.net.in.impl.CommandPacket.handle(CommandPacket.java:54)
[2015-10-25 05:45:32] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-25 05:45:32] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-25 05:45:32] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-25 05:45:32] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-25 05:45:32] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-25 09:31:54] java.lang.NullPointerException
[2015-10-25 09:31:54] java.lang.NullPointerException
[2015-10-25 09:31:54] 	at com.vencillio.rs2.entity.player.net.Client.send(Client.java:329)
[2015-10-25 09:31:54] 	at com.vencillio.rs2.entity.player.net.out.impl.SendLogout.execute(SendLogout.java:13)
[2015-10-25 09:31:54] 	at com.vencillio.rs2.entity.player.Player.logout(Player.java:1444)
[2015-10-25 09:31:54] 	at com.vencillio.rs2.entity.World.process(World.java:332)
[2015-10-25 09:31:54] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-25 09:31:54] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-25 10:40:29] java.lang.NumberFormatException: For input string: "romania clan"
[2015-10-25 10:40:29] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2015-10-25 10:40:29] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-25 10:40:29] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-25 10:40:29] 	at com.vencillio.rs2.entity.player.net.in.impl.StringInputPacket.handle(StringInputPacket.java:41)
[2015-10-25 10:40:29] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-25 10:40:29] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-25 10:40:29] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-25 10:40:29] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-25 10:40:29] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-25 10:43:48] java.lang.NumberFormatException: For input string: "7m"
[2015-10-25 10:43:48] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2015-10-25 10:43:48] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-25 10:43:48] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-25 10:43:48] 	at com.vencillio.rs2.entity.player.net.in.impl.StringInputPacket.handle(StringInputPacket.java:41)
[2015-10-25 10:43:48] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-25 10:43:48] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-25 10:43:48] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-25 10:43:48] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-25 10:43:48] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-25 12:49:49] java.lang.IndexOutOfBoundsException: Readable byte limit exceeded: 12
[2015-10-25 12:49:49] 	at org.jboss.netty.buffer.AbstractChannelBuffer.readByte(AbstractChannelBuffer.java:236)
[2015-10-25 12:49:49] 	at com.vencillio.core.network.StreamBuffer$InBuffer.readByte(StreamBuffer.java:120)
[2015-10-25 12:49:49] 	at com.vencillio.core.network.StreamBuffer$InBuffer.readByte(StreamBuffer.java:107)
[2015-10-25 12:49:49] 	at com.vencillio.core.network.StreamBuffer$InBuffer.readShort(StreamBuffer.java:467)
[2015-10-25 12:49:49] 	at com.vencillio.core.network.StreamBuffer$InBuffer.readShort(StreamBuffer.java:412)
[2015-10-25 12:49:49] 	at com.vencillio.rs2.entity.player.net.in.impl.ItemPackets.handle(ItemPackets.java:748)
[2015-10-25 12:49:49] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-25 12:49:49] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-25 12:49:49] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-25 12:49:49] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-25 12:49:49] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-25 17:51:07] java.lang.NullPointerException
[2015-10-25 17:51:07] java.lang.NullPointerException
[2015-10-25 19:27:17] java.lang.NullPointerException
[2015-10-25 19:27:17] 	at com.vencillio.rs2.content.DropTable.displayNpc(DropTable.java:177)
[2015-10-25 19:27:17] 	at com.vencillio.rs2.entity.player.net.in.impl.ClickButtonPacket.handle(ClickButtonPacket.java:115)
[2015-10-25 19:27:17] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-25 19:27:17] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-25 19:27:17] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-25 19:27:17] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-25 19:27:17] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-25 21:50:41] java.lang.NumberFormatException: For input string: "500k"
[2015-10-25 21:50:41] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2015-10-25 21:50:41] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-25 21:50:41] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-25 21:50:41] 	at com.vencillio.rs2.entity.player.net.in.impl.StringInputPacket.handle(StringInputPacket.java:41)
[2015-10-25 21:50:41] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-25 21:50:41] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-25 21:50:41] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-25 21:50:41] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-25 21:50:41] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-25 21:50:57] java.lang.NumberFormatException: For input string: "500k"
[2015-10-25 21:50:57] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2015-10-25 21:50:57] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-25 21:50:57] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-25 21:50:57] 	at com.vencillio.rs2.entity.player.net.in.impl.StringInputPacket.handle(StringInputPacket.java:41)
[2015-10-25 21:50:57] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-25 21:50:57] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-25 21:50:57] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-25 21:50:57] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-25 21:50:57] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-25 21:51:16] java.lang.NumberFormatException: For input string: "500k"
[2015-10-25 21:51:16] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2015-10-25 21:51:16] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-25 21:51:16] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-25 21:51:16] 	at com.vencillio.rs2.entity.player.net.in.impl.StringInputPacket.handle(StringInputPacket.java:41)
[2015-10-25 21:51:16] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-25 21:51:16] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-25 21:51:16] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-25 21:51:16] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-25 21:51:16] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-25 22:12:48] java.lang.NumberFormatException: For input string: "100k"
[2015-10-25 22:12:48] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2015-10-25 22:12:48] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-25 22:12:48] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-25 22:12:48] 	at com.vencillio.rs2.entity.player.net.in.impl.StringInputPacket.handle(StringInputPacket.java:41)
[2015-10-25 22:12:48] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-25 22:12:48] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-25 22:12:48] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-25 22:12:48] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-25 22:12:48] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-26 03:11:34] java.lang.NullPointerException
[2015-10-26 03:11:34] java.lang.NullPointerException
[2015-10-26 03:53:31] java.lang.NullPointerException
[2015-10-26 03:53:31] java.lang.NullPointerException
[2015-10-26 05:14:38] java.lang.NumberFormatException: For input string: "500k"
[2015-10-26 05:14:38] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[2015-10-26 05:14:38] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-26 05:14:38] 	at java.lang.Integer.parseInt(Unknown Source)
[2015-10-26 05:14:38] 	at com.vencillio.rs2.entity.player.net.in.impl.StringInputPacket.handle(StringInputPacket.java:41)
[2015-10-26 05:14:38] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-26 05:14:38] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-26 05:14:38] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-26 05:14:38] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-26 05:14:38] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-26 07:12:01] java.lang.NullPointerException
[2015-10-26 07:12:01] 	at com.vencillio.rs2.content.GenieReset.handle(GenieReset.java:118)
[2015-10-26 07:12:01] 	at com.vencillio.rs2.entity.player.net.in.impl.ClickButtonPacket.handle(ClickButtonPacket.java:909)
[2015-10-26 07:12:01] 	at com.vencillio.rs2.entity.player.net.in.PacketHandler.handlePacket(PacketHandler.java:151)
[2015-10-26 07:12:01] 	at com.vencillio.rs2.entity.player.net.Client.processIncomingPackets(Client.java:211)
[2015-10-26 07:12:01] 	at com.vencillio.rs2.entity.World.process(World.java:319)
[2015-10-26 07:12:01] 	at com.vencillio.core.GameThread.cycle(GameThread.java:124)
[2015-10-26 07:12:01] 	at com.vencillio.core.GameThread.run(GameThread.java:139)
[2015-10-26 08:18:07] java.lang.NullPointerException
[2015-10-26 08:18:07] java.lang.NullPointerException
[2015-10-26 08:18:26] com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

Last packet sent to the server was 18901 ms ago.
[2015-10-26 08:18:26] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2015-10-26 08:18:26] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-26 08:18:26] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-26 08:18:26] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1074)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3009)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2895)
[2015-10-26 08:18:26] Exception in thread "DatabaseConnection" 
[2015-10-26 08:18:26] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3438)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2046)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1964)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1949)
[2015-10-26 08:18:26] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:222)
[2015-10-26 08:18:26] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-26 08:18:26] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-26 08:18:26] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-26 08:18:26] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-26 08:18:26] 	at java.lang.Thread.run(Unknown Source)
[2015-10-26 08:18:26] Caused by: java.net.SocketTimeoutException: Read timed out
[2015-10-26 08:18:26] 	at java.net.SocketInputStream.socketRead0(Native Method)
[2015-10-26 08:18:26] 	at java.net.SocketInputStream.socketRead(Unknown Source)
[2015-10-26 08:18:26] 	at java.net.SocketInputStream.read(Unknown Source)
[2015-10-26 08:18:26] 	at java.net.SocketInputStream.read(Unknown Source)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:113)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:160)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:188)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2452)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2906)
[2015-10-26 08:18:26] 	... 15 more
[2015-10-26 08:18:26] com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

Last packet sent to the server was 18905 ms ago.
[2015-10-26 08:18:26] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2015-10-26 08:18:26] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-26 08:18:26] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-26 08:18:26] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1074)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3009)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2895)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3438)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2046)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1964)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1949)
[2015-10-26 08:18:26] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:222)
[2015-10-26 08:18:26] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-26 08:18:26] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-26 08:18:26] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-26 08:18:26] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-26 08:18:26] 	at java.lang.Thread.run(Unknown Source)
[2015-10-26 08:18:26] Caused by: java.net.SocketTimeoutException: Read timed out
[2015-10-26 08:18:26] 	at java.net.SocketInputStream.socketRead0(Native Method)
[2015-10-26 08:18:26] 	at java.net.SocketInputStream.socketRead(Unknown Source)
[2015-10-26 08:18:26] 	at java.net.SocketInputStream.read(Unknown Source)
[2015-10-26 08:18:26] 	at java.net.SocketInputStream.read(Unknown Source)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:113)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:160)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:188)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2452)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2906)
[2015-10-26 08:18:26] 	... 15 more
[2015-10-26 08:18:26] com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

Last packet sent to the server was 18902 ms ago.
[2015-10-26 08:18:26] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2015-10-26 08:18:26] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-26 08:18:26] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[2015-10-26 08:18:26] 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1074)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3009)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2895)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3438)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2046)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1964)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1949)
[2015-10-26 08:18:26] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:222)
[2015-10-26 08:18:26] 	at com.vencillio.core.network.mysql.ExternalDatabase$InteralQuery.call(ExternalDatabase.java:1)
[2015-10-26 08:18:26] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2015-10-26 08:18:26] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2015-10-26 08:18:26] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2015-10-26 08:18:26] 	at java.lang.Thread.run(Unknown Source)
[2015-10-26 08:18:26] Caused by: java.net.SocketTimeoutException: Read timed out
[2015-10-26 08:18:26] 	at java.net.SocketInputStream.socketRead0(Native Method)
[2015-10-26 08:18:26] 	at java.net.SocketInputStream.socketRead(Unknown Source)
[2015-10-26 08:18:26] 	at java.net.SocketInputStream.read(Unknown Source)
[2015-10-26 08:18:26] 	at java.net.SocketInputStream.read(Unknown Source)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:113)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:160)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:188)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2452)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2906)
[2015-10-26 08:18:26] 	... 15 more
[2015-10-26 08:18:26] java.lang.NullPointerException
[2015-10-26 08:18:26] 	at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2162)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2138)
[2015-10-26 08:18:26] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1853)
[2015-10-26 08:18:26] 	at com.vencillio.core.network.mysql.ExternalDatabase$DatabaseConnection.ping(ExternalDatabase.java:148)
[2015-10-26 08:18:26] 	at com.vencillio.core.network.mysql.ExternalDatabase$DatabaseConnection.access$8(ExternalDatabase.java:143)
[2015-10-26 08:18:26] 	at com.vencillio.core.network.mysql.ExternalDatabase.run(ExternalDatabase.java:409)
[2015-10-26 08:18:26] 	at java.lang.Thread.run(Unknown Source)
